language: smalltalk

sudo: false

os:
  - linux
  - osx
  
smalltalk:
  - Pharo-7.0
  - Pharo-6.1
  - Pharo-5.0

env:
  matrix:
    - CI_FILE=.smalltalk.ston
    - CI_FILE=.stress.smalltalk.ston
    
script:
  - travis_wait "$SMALLTALK_CI_HOME/run.sh" ${CI_FILE}